### ISSUE TITLE
Add Japanese vehicle loadouts

### ISSUE THREAD

**Issue by DarkMessiah27** [DarkMessiah27/2.PzD-Mission-Template#36]
Add a vehicle loadout specific to the Japanese.

Use the existing German and Russian vehicle loadouts as an example and use the generic vehicle loadout definitions (found in vehGearGEN.sqf) as much as possible. Furthermore, try to keep the amount of equipment roughly the same as the other vehicle loadouts.

**Comment by HeinrichFalk** [comment]
Can be closed - as Japanese loadouts has been removed
